version: '3.8'

services:
  # =============
  # 1. DB SERVICE
  # =============
  postgres_db:
    image: postgres:16-alpine
    container_name: material_db
    restart: unless-stopped
    env_file:
      - ./server_core/.env
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d material_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  # ============
  # 2. SERVER CORE (FastAPI + EfficientNet)
  # ============
  server_core:
    build: 
      context: ./server_core
      dockerfile: Dockerfile
    image: longsoncement/material_server:v1.0
    container_name: material_server
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./server_core/.env
    networks:
      - material_network
    depends_on:
      postgres_db:
        condition: service_healthy

    # ---------------------------------------------------------
    #[TÙY CHỌN GPU]: Bỏ comment khối 'deploy' dưới đây nếu Server có Card NVIDIA
    # ---------------------------------------------------------
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

    # ==============
    # 3. CLIENT EDGE
    # ==============
    client_edge:
      build:
        context: ./client_edge
        dockerfile: Dockerfile
      image: longsoncement/material_client:v1.0
      restart: unless-stopped
      networks:
      - material_network
      env_file:
      - ./client_edge/.env
      depends_on:
      - server_core

    # ===============
    # 4. PG ADMIN
    # ===============
    pgadmin:
      image: dpage/pgadmin4
      container_name: material_pgadmin
      restart: unless-stopped
      env_file:
        - ./server_core/.env # Có thể tái sử dụng file env hoặc tạo file riêng
      ports:
        - "5050:80"
      networks:
        - material_network
      depends_on:
        postgres_db:
          condition: service_healthy

# Định nghĩa Volume và Network rõ ràng (Học hỏi điểm tốt từ repo Github)
volumes:
  postgres_data:
    name: material_postgres_data

networks:
  material_network:
    name: material_internal_net
    driver: bridge
    

      
